### ISSUE TITLE
Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by yan12125** [mikkeloscar/arch-travis#33] opened 2017-12-22 03:24 UTC
I got the following error message for all recent builds:
```
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
```
Is arch-travis or Arch Linux itself broken?

**Comment by vufa** [comment] 2017-12-22 05:05
The same problem as you have, when I use `wget`:
```
Generating locales...
  en_US.UTF-8... done
Generation complete.
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   865    0   865    0     0    870      0 --:--:-- --:--:-- --:--:--   870
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
The command "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash" exited with 127.
```

**Comment by mikkeloscar** [comment] 2017-12-22 21:09
Looks like an issue with the latest systemd package. If I pin it like in #34 the build works.

I don't have much time these days, so feel free to file a bug in Archlinux if you can. I'll merge #34 as a temporary fix.

**Comment by yan12125** [comment] 2017-12-23 03:54
Thanks for the workaround! Now it works just fine as usual.

I'm willing to report a bug to Arch Linux, but I have no idea what's under the hood. Mind sharing how did you find that systemd broke things?

**Comment by vufa** [comment] 2017-12-23 05:15
The problem is solved, everything is working fine, thanks.

**Comment by mikkeloscar** [comment] 2017-12-26 10:42
Opened a bug here: https://bugs.archlinux.org/task/56867

**Comment by yan12125** [comment] 2018-01-02 05:37
Hello, this is broken again: https://travis-ci.org/yan12125/aur/builds/324003454

Looks like systemd is added to group ```base-devel```, so it's installed anyway:
```
:: systemd is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n] 
```
And it's also updated in ```archlinux-bootstrap-2018.01.01-x86_64.tar.gz```:
```
warning: systemd-236.0-2 is up to date -- reinstalling
```

**Comment by 2m** [comment] 2018-01-02 07:41
Yup. Just noticed this problem here as well: https://travis-ci.org/2m/coursier-pkgbuild/builds/324036798

**Comment by mikkeloscar** [comment] 2018-01-03 06:27
Added a quick fix in #35 to select the previous ISO which has a working systemd version. This will only work for this month, but gives some time to figure out a better solution.

Since systemd is now part of the latest ISO I imagine it will be hard to use that in some way, since you can't even install the previous systemd version without it failing.

**Comment by anthraxx** [comment] 2018-02-01 01:54
So what are we doing now? It stopped working again

**Comment by mikkeloscar** [comment] 2018-02-01 06:38
@anthraxx I prepared this #37 (and just merged it now).

Unfortunately I have not had time to find a real fix yet :(

**Comment by mikkeloscar** [comment] 2018-03-03 15:28
Fixed by using docker instead of chroot.

See README.md (and #40) for updated configuration.

**Closed as completed by mikkeloscar** 2018-03-03 15:28 UTC
